using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Media;
using System.Runtime.Remoting.Channels;
using System.Runtime.Versioning;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;


//References:
//ChatGPT www.ChatGPT.com
//How to Play Music In C# (Simple) - https://www.youtube.com/watch?v=uZlz1SSisYY
namespace POEpart1
{

    internal class Program
    {
        static string name; //Global variable for the name of the user

        static void Main(string[] args)
        {
            PlaySound("IntroSound.wav");
            Greeting();
            Cyperchat();
        }

        //Method inspired by How to Play Music In C# (Simple)
        public static void PlaySound(string soundFilePath)
        {
            try
            {
                using (SoundPlayer player = new SoundPlayer(soundFilePath))
                {
                    player.Play();
                }
            }
            catch(Exception ex) 
            {
                Console.WriteLine($"Error playing sound: {ex.Message}");
            }
            
        }

        //Method created by ChatGPT to display ASCII art
        static void DisplayLogo()
        {
            Console.WriteLine(@"  ____            _                  _                 
     / ___|___  _ __ | |_ _ __ _   _   / \   ___ ___  ___ 
    | |   / _ \| '_ \| __| '__| | | | / _ \ / __/ __|/ _ \
    | |__| (_) | | | | |_| |  | |_| |/ ___ \\__ \__ \  __/
     \____\___/|_| |_|\__|_|   \__, /_/   \_\___/___/\___|
                               |___/                     
       Cybersecurity Awareness Bot
            ");
        }

        static void Greeting()
        {
            DisplayLogo();

            Console.WriteLine("--------------------------------------------------");
            Console.WriteLine("           Welcome to the Cyber Chat!");
            Console.WriteLine("--------------------------------------------------");
            while (true)
            {
                Console.Write("Please enter your name: ");
                name = Console.ReadLine();
                if (string.IsNullOrWhiteSpace(name) || name.Any(char.IsDigit))
                {
                    Console.WriteLine("Please enter a valid name and don't include numbers.");
                }
                else
                {
                    Console.WriteLine($"Hello, {name}! I'm your virtual assistant for online safety.");
                    Console.WriteLine("I'm here to help you with your online safety questions.");
                    Console.WriteLine();
                    Console.WriteLine("--------------------------------------------------");
                    break;
                }
            }
        }


        static void Cyperchat()
        {
            //generated by ChatGPT
            //-------------------------------------------------
            Dictionary<string, string> responses = new Dictionary<string, string>
            {
                { "how are you", "I'm doin' very well! Thanks for asking!" }, //I made
                { "what is your purpose", "My purpose is to help you educate you on cybersequrity related questions." }, //I made
                { "what can I ask you about", "You can ask me about anything cybersecurity related, such as: What are passwords?" }, //I made
                { "password", "Remember, always use strong, unique passwords for your accounts." },
                { "phishing", "Be cautious with emails asking for personal information. Always verify the sender!" },
                { "two-factor authentication", "Enable two-factor authentication (2FA) on your accounts for an added layer of security." },
                { "malware", "Ensure you have updated anti-virus software to protect against malware and other malicious software." },
                { "vpn", "Use a VPN (Virtual Private Network) when browsing on public Wi-Fi to secure your data." },
                { "firewall", "Make sure your firewall is enabled to protect your device from unauthorized access." },
                { "ransomware", "Never click on suspicious links or open unexpected attachments to avoid ransomware attacks." },
                { "data encryption", "Use data encryption to secure sensitive information, both when stored and in transit." },
                { "social engineering", "Be wary of unsolicited calls or messages asking for personal or financial information." },
                { "software updates", "Always install software and security updates promptly to fix vulnerabilities in your system." },
                { "backup", "Regularly back up your important data to ensure you can recover it in case of an attack or system failure." },
                { "password manager", "Consider using a password manager to store and manage your passwords securely." },
                { "strong passwords", "Create passwords that are at least 12 characters long, using a mix of letters, numbers, and special characters." },
                { "public wifi", "Avoid accessing sensitive accounts or making transactions when using public Wi-Fi networks."}
            };
            //-------------------------------------------------

            //Only works with one question at a time, so no two questions at the same time
            while (true)
            {

                Console.WriteLine();
                Console.Write($"Please ask your question {name}: ");


                string question = Console.ReadLine().ToLower();

                if (string.IsNullOrWhiteSpace(question) || question.Any(char.IsDigit))
                {
                    Console.WriteLine("--------------------------------------------------");
                    Console.WriteLine($"{name}, Please enter a valid question and don't include numbers.");
                    continue;
                }

                //Generated by ChatGPT to remove punctuation and special characters
                question = Regex.Replace(question, @"[^\w\s]", "");

                Console.WriteLine();
                Console.WriteLine("--------------------------------------------------");

                //Generated by ChatGPT to check if the question contains any of the keys in the dictionary
                string matchKey = responses.Keys.FirstOrDefault(k => question.Contains(k));

                if (matchKey != null)
                {
                    Console.WriteLine();
                    Console.WriteLine($"Answer: {responses[matchKey]}");
                    Console.WriteLine();
                    Console.WriteLine("--------------------------------------------------");
                    Console.WriteLine($"Would you like to ask another question {name}? (yes/no)");
                    Console.Write("Enter: ");

                    string anotherQuestion = Console.ReadLine().ToLower();
                    Console.WriteLine("--------------------------------------------------");
                    if (anotherQuestion == "yes")
                    {
                        continue;
                    }
                    else if (string.IsNullOrWhiteSpace(anotherQuestion) || anotherQuestion.Any(char.IsDigit))
                    {
                        Console.WriteLine();
                        Console.WriteLine($"{name}, Please enter a valid question and don't include numbers.");
                    }
                    else
                    {
                        Console.WriteLine($"Thank you for using the Cyber Chat {name}! Stay safe online!");
                        break;
                    }
                }
                else
                {
                    Console.WriteLine($"I'm sorry {name}, I don't have an answer for that question.");
                    Console.WriteLine("If you want to ask another question, please type 'yes'. If you want to exit, type 'no'.");

                    string yn = Console.ReadLine().ToLower();
                    if (yn == "yes")
                    {
                        Console.Write($"Please ask your question {name}:  ");
                    }
                    else if (yn == "no")
                    {
                        Console.WriteLine($"Thank you {name} for using the Cyber Chat! Stay safe online!");
                        break;
                    }
                    else if (string.IsNullOrWhiteSpace(yn) || yn.Any(char.IsDigit))
                    {
                        Console.WriteLine($"{name}, Please enter a valid question and don't include numbers.");
                    }
                }
            }
        }
    }
}
