using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//References:
//ChatGPT www.ChatGPT.com

namespace POEpart1.Dictionaries
{
    public static class MainResponces
    {
        //generated by ChatGPT
        //-------------------------------------------------
        //Main responses for common questions
        public static Dictionary<string, string[]> responses = new Dictionary<string, string[]>
        {
            ["how are you"] = new[]
            {
                "I'm doing great—thanks for asking!",
                "All systems green over here!",
                "Feeling fantastic, how about you?",
                "I'm well and ready to help!",
                "Pretty good, thanks! What can I do for you today?"
            },

            ["what is your purpose"] = new[]
            {
                "My purpose is to educate you on cybersecurity topics.",
                "I'm here to help you learn about staying safe online.",
                "I exist to answer your questions about cyber safety.",
                "My job is to guide you through security best practices.",
                "I’m designed to assist you with all things cybersecurity."
            },

            ["what can I ask you about"] = new[]
            {
                "You can ask me about passwords, malware, phishing, and more.",
                "Feel free to quiz me on any cybersecurity topic you like.",
                "I can discuss topics from VPNs to data encryption.",
                "Ask me about firewalls, backups, or two-factor authentication.",
                "I'm here for anything security-related—from viruses to Wi-Fi safety."
            },

            ["virus"] = new[]
            {
                "A virus is malicious software that replicates by infecting files.",
                "Think of a computer virus like a biological one—it spreads file to file.",
                "This malware attaches itself to programs and can corrupt data.",
                "A virus self-replicates and may damage your system or steal info.",
                "In cybersecurity, a virus is code that hides in other executables."
            },

            ["password"] = new[]
            {
                "A password is a secret string you use to protect your accounts.",
                "Think of your password as the key to your digital front door.",
                "It’s a private phrase that only you should know and never share.",
                "Strong passwords mix letters, numbers, and symbols for security.",
                "Treat your password like cash—keep it safe and unique per site."
            },

            ["phishing"] = new[]
            {
                "Phishing is a scam where attackers pose as someone you trust.",
                "It often uses fake emails or websites to steal your credentials.",
                "Think twice before clicking links in unsolicited messages.",
                "Phishing exploits human trust to capture your private info.",
                "Always verify the sender before entering passwords online."
            },

            ["two-factor authentication"] = new[]
            {
                "Two-factor authentication (2FA) adds a second step after your password.",
                "2FA might send you a one-time code via SMS or an authenticator app.",
                "This extra layer helps keep attackers out, even if they have your password.",
                "Enable 2FA to make it much harder for someone to hijack your account.",
                "With 2FA, you need something you know (password) and something you have (code)."
            },

            ["malware"] = new[]
            {
                "Malware is any software designed to harm or exploit your device.",
                "This umbrella term covers viruses, worms, ransomware, and more.",
                "Malware can steal, encrypt, or delete your data without permission.",
                "Always keep your antivirus up to date to catch new malware strains.",
                "Downloading from untrusted sources is a common way to get malware."
            },

            ["vpn"] = new[]
            {
                "A VPN creates a secure, encrypted tunnel between you and the internet.",
                "With a VPN, your data is hidden from eavesdroppers on public Wi-Fi.",
                "Virtual Private Networks mask your IP address for added privacy.",
                "A VPN can help keep your browsing history private from your ISP.",
                "Use a reputable VPN service whenever you’re on an unsecured network."
            },

            ["firewall"] = new[]
            {
                "A firewall monitors and filters incoming and outgoing network traffic.",
                "Think of a firewall as a gatekeeper for your computer’s connections.",
                "It can block unauthorized access while allowing safe communications.",
                "Most operating systems include a built-in software firewall you can enable.",
                "A hardware firewall sits between your router and the internet for extra protection."
            },

            ["ransomware"] = new[]
            {
                "Ransomware encrypts your files and demands payment for the key.",
                "Never pay the ransom—there’s no guarantee you’ll get your data back.",
                "Keep offline backups so you can restore your files if attacked.",
                "Ransomware often spreads via malicious email attachments.",
                "Invest in good antivirus software to detect ransomware before it runs."
            },

            ["data encryption"] = new[]
            {
                "Data encryption scrambles your information so only authorized parties can read it.",
                "Encrypted data looks like gibberish unless you have the decryption key.",
                "Use encryption at rest (on disk) and in transit (over the network) for full protection.",
                "Many apps offer end-to-end encryption so even the provider can’t read your data.",
                "Strong encryption algorithms keep your private info safe from prying eyes."
            },

            ["social engineering"] = new[]
            {
                "Social engineering tricks people into giving away confidential information.",
                "It relies on psychological manipulation rather than technical hacking.",
                "Attackers might pretend to be IT support or a trusted colleague.",
                "Always verify requests for sensitive data, even if they seem urgent.",
                "When in doubt, call the person back at a known number before sharing info."
            },

            ["software updates"] = new[]
            {
                "Software updates patch security holes and fix bugs.",
                "Keeping programs up to date is one of the easiest ways to stay secure.",
                "Many attacks exploit vulnerabilities that vendors have already patched.",
                "Enable automatic updates to ensure you never miss a critical patch.",
                "Outdated software is a common entry point for malware infections."
            },

            ["backup"] = new[]
            {
                "A backup is a copy of your data stored separately in case of loss.",
                "Follow the 3-2-1 rule: three copies, on two different media, one off-site.",
                "Regular backups let you recover quickly from hardware failure or ransomware.",
                "Test your backups occasionally to make sure they actually work.",
                "Cloud backup services can automate the process for you."
            },

            ["password manager"] = new[]
            {
                "A password manager securely stores your login credentials in one place.",
                "It can generate long, random passwords so you never reuse the same one.",
                "Most password managers autofill your passwords in the browser or apps.",
                "Protect your vault with a strong master password and enable 2FA.",
                "Using a password manager is far safer than memorizing or writing down passwords."
            },

            ["strong passwords"] = new[]
            {
                "Strong passwords are at least 12 characters long and mix letters, numbers, and symbols.",
                "Avoid dictionary words or easily guessed phrases like birthdays or pet names.",
                "A passphrase of unrelated words can be both strong and memorable.",
                "Use uppercase, lowercase, digits, and special characters for best results.",
                "Change your passwords regularly and never reuse them across sites."
            },

            ["public wifi"] = new[]
            {
                "Public Wi-Fi networks are often unencrypted and open to eavesdropping.",
                "Avoid logging into banking or email accounts unless you use a VPN.",
                "Always check the network name with staff to avoid ‘evil twin’ hotspots.",
                "Set your Wi-Fi profile to ‘public’ so your device won’t share files or printers.",
                "Turn off automatic connection to open networks to prevent unwanted joins."
            }
        };
        //-------------------------------------------------
        // Follow-up responses for specific questions
        public static Dictionary<string, string[]> followUp = new Dictionary<string, string[]>
        {
            ["how are you"] = new[]
            {
                "I’m running at full efficiency today—my security modules are all green and ready to assist you!",
                "All systems are operational, with zero detected threats in my monitoring queue.",
                "Feeling robust—my last update patched several vulnerabilities, so I’m in top form.",
                "I'm operating smoothly, thanks to continuous health checks and real-time threat intelligence.",
                "At peak performance—no critical alerts on my dashboard, so let’s dive into cybersecurity!"
            },

            ["what is your purpose"] = new[]
            {
                "I exist to demystify cybersecurity concepts and guide you through best practices.",
                "My core mission is to help you recognize and mitigate online threats before they become risks.",
                "I analyze your questions and deliver practical advice on securing your digital life.",
                "Think of me as your personal cyber-safety coach: I spot vulnerabilities and suggest fixes.",
                "I’m here to translate technical jargon into clear steps you can follow to stay safe online."
            },

            ["what can i ask you about"] = new[]
            {
                "Beyond basics like passwords and malware, you can quiz me on threat modeling or incident response.",
                "I can walk you through protocols (SSL/TLS), authentication schemes (OAuth, SAML), and more.",
                "Ask me about secure coding, cloud security, network segmentation, or even zero-trust architectures.",
                "From ransomware trends to social engineering case studies, I’ve got detailed insights.",
                "Curious about compliance frameworks (GDPR, PCI-DSS)? I can break them down too."
            },

            ["virus"] = new[]
            {
                "Computer viruses inject their code into executables; they often use polymorphism to evade signature detection.",
                "Some viruses lie dormant until a specific trigger—like a date or user action—before activating payloads.",
                "Modern antivirus uses heuristics and behavioral analysis to catch viruses, not just known signatures.",
                "Viruses can spread via removable media, network shares, or even malformed email attachments.",
                "Advanced viruses may disable security software or open backdoors for further exploitation."
            },

            ["password"] = new[]
            {
                "Passwords should be stored hashed and salted using algorithms like bcrypt or Argon2 to prevent theft.",
                "Avoid reusing passwords across sites—if one breach happens, attackers can pivot to your other accounts.",
                "Consider passphrases (e.g. ‘correct horse battery staple’) for higher entropy and easier memorability.",
                "Use a password strength meter (like zxcvbn) to gauge how resistant your password is to guessing.",
                "Never share passwords and avoid writing them down; a password manager can handle storage securely."
            },

            ["phishing"] = new[]
            {
                "Phishers craft emails or sites that mimic real ones—check URLs carefully and look for typos or odd domains.",
                "They often leverage urgency (‘your account will close!’) to trick you into clicking without thinking.",
                "Some attacks use spear-phishing: highly personalized messages based on information scraped about you.",
                "Phishing kits on the dark web make it trivial for novice attackers to launch credential-harvesting sites.",
                "To defend, enable email filtering, train users on red flags, and test with simulated phishing drills."
            },

            ["two-factor authentication"] = new[]
            {
                "Beyond SMS codes, stronger 2FA methods include TOTP apps (Google Authenticator) or hardware keys (YubiKey).",
                "SMS-based 2FA is vulnerable to SIM-swap attacks—consider app-based or U2F keys for critical accounts.",
                "2FA drastically reduces account takeover risk: even if your password leaks, the attacker needs the second factor.",
                "Implement push-based 2FA with fraud detection to see real-time prompts before approving logins.",
                "Remember to save recovery codes in a secure location in case you lose access to your 2FA device."
            },

            ["malware"] = new[]
            {
                "Malware families include worms, trojans, spyware, rootkits and more—each with unique behaviors.",
                "Fileless malware lives only in memory, making it harder to detect with traditional antivirus scans.",
                "Many modern threats use command-and-control (C2) servers to receive instructions post-infection.",
                "Sandboxing and behavioral analysis are key defenses, as malware often changes its code on each run.",
                "Keep your OS and apps patched; unpatched vulnerabilities are the primary entry point for malware."
            },

            ["vpn"] = new[]
            {
                "VPN protocols differ: WireGuard is lightweight and fast, OpenVPN is highly configurable, IKEv2 is good on mobile.",
                "A VPN encrypts traffic—on public Wi-Fi it prevents eavesdroppers from intercepting your data.",
                "Select VPN servers in privacy-friendly jurisdictions to avoid data logging requirements.",
                "Be cautious of free VPNs—they may log data or inject ads; choose reputable paid services.",
                "Use DNS over HTTPS (DoH) or DNS over TLS for extra privacy alongside your VPN connection."
            },

            ["firewall"] = new[]
            {
                "Configure stateful inspection: firewalls track connection states and block out-of-scope traffic.",
                "Use both network-level (router) and host-based (OS) firewalls for layered defense.",
                "Implement application-layer gateways (proxies) to inspect and filter HTTP or FTP traffic.",
                "Regularly review firewall rules to remove stale entries and tighten access controls.",
                "For enterprise, consider next-gen firewalls with intrusion prevention and deep packet inspection."
            },

            ["ransomware"] = new[]
            {
                "Ransomware-as-a-Service (RaaS) allows affiliates to launch attacks without coding skills.",
                "Attackers often exfiltrate data before encryption, then threaten to leak it if you don’t pay.",
                "Immutable backups (WORM storage) and air-gapped archives are your best recovery options.",
                "Use endpoint detection and response (EDR) tools to spot ransomware behavior early.",
                "Segment critical systems so ransomware can’t spread laterally across your network."
            },

            ["data encryption"] = new[]
            {
                "Symmetric encryption (AES-256) is fast for large datasets; asymmetric (RSA, ECC) secures key exchange.",
                "Implement TLS 1.2/1.3 for data in transit, and full-disk or file-level encryption for data at rest.",
                "Key management is critical—use hardware security modules (HSMs) or cloud KMS to safeguard keys.",
                "Encrypt backups and verify them regularly—unencrypted backups defeat the purpose.",
                "Avoid custom crypto—always rely on vetted, open-source libraries to prevent implementation flaws."
            },

            ["social engineering"] = new[]
            {
                "Pretexting, baiting, and quid pro quo are classic social engineering tactics—always validate requests.",
                "Regular security awareness training helps users spot manipulation techniques.",
                "Phishing is a subset; social engineering also includes in-person tailgating and help-desk scams.",
                "Simulate attacks (red team exercises) to measure and improve human defenses.",
                "Establish clear protocols for sensitive requests—e.g. multi-person approval for data access."
            },

            ["software updates"] = new[]
            {
                "Use automated patch management to scan, test, and deploy updates on a regular schedule.",
                "Prioritize critical patches for exploitable vulnerabilities with active public exploits.",
                "Maintain a test environment to validate updates before rolling them into production.",
                "Leverage OS vendor tools (WSUS for Windows, yum/apt automation for Linux) for centralized control.",
                "Monitor CVE feeds so you know exactly which updates address your exposure."
            },

            ["backup"] = new[]
            {
                "Adopt the 3-2-1 rule: keep three copies, on two media types, with one copy offsite or cloud-based.",
                "Use incremental or differential backups to reduce storage use and speed up routine jobs.",
                "Encrypt backups at rest and in transit to protect against unauthorized access.",
                "Regularly test restore procedures to ensure your backups are viable when disaster strikes.",
                "Implement retention policies that balance data availability with compliance requirements."
            },

            ["password manager"] = new[]
            {
                "Choose a manager with zero-knowledge architecture so even the provider can’t read your vault.",
                "Enable multi-factor authentication on your password manager for an extra security layer.",
                "Regularly audit stored credentials for weak or duplicate passwords.",
                "Use features like secure note storage and emergency access contacts wisely.",
                "Keep the manager software updated and back up its encrypted vault periodically."
            },

            ["strong passwords"] = new[]
            {
                "Generate passphrases with high entropy—Diceware is an effective method using random word lists.",
                "Aim for at least 16 characters; each additional character exponentially increases brute-force time.",
                "Avoid predictable substitutions (e.g. ‘P@ssw0rd’)—attackers know common leet tweaks.",
                "Use unique passwords per account so one breach doesn’t cascade across services.",
                "Consider biometrics or hardware tokens to complement passwords for critical systems."
            },

            ["public wifi"] = new[]
            {
                "Set your network profile to Public so your OS firewall applies stricter rules automatically.",
                "Always use a VPN and HTTPS to encrypt traffic on untrusted networks.",
                "Watch out for rogue hotspots—confirm SSIDs with venue staff before connecting.",
                "Disable file and printer sharing when on public networks to avoid unintended access.",
                "Turn off Wi-Fi auto-join to prevent connecting to unfamiliar or malicious networks."
            }
        };


        //-------------------------------------------------
        //Sentiment detection responses
        public static Dictionary<string, string> sentimateDetection = new Dictionary<string, string>
        {
            {"worried", "It's completely understandable to feel that way."},
            {"frustrated", "I know this can be tricky—let’s work through it step by step."},
            {"curious", "Great—you’ve got a curious mind! Let me explain in more detail."},
            {"confused", "I’m sorry if it’s confusing; let me clarify that for you."},
            {"concerned", "I hear your concern. Let’s address it together."},
            {"anxious", "It’s normal to feel anxious about security. I’ll guide you through the essentials."},
            {"overwhelmed", "I understand this can feel overwhelming. We’ll take it one piece at a time."}
        };



        //-------------------------------------------------
        // Memory reminders for topics the user has already asked about
        public static Dictionary<string, string> memoryValue = new Dictionary<string, string>
        {
            { "how are you", "You asked how I was doing earlier—I'm still running smoothly and ready to help!" },
            { "what is your purpose", "Last time you wondered about my purpose; I exist to guide you through cybersecurity best practices." },
            { "what can i ask you about", "You wanted to know what you could ask—feel free to quiz me on anything from passwords to firewalls." },
            { "virus", "I remember we talked about viruses; keep your OS and applications patched to reduce your risk." },
            { "password", "We discussed passwords before; don’t forget to use long, unique passwords and consider a manager." },
            { "phishing", "You asked about phishing; always double-check links and sender addresses before clicking." },
            { "two-factor authentication", "We covered 2FA previously—enabling it adds a powerful extra layer of account protection." },
            { "malware", "We talked about malware; make sure your antivirus definitions are up to date and scan regularly." },
            { "vpn", "Recall our VPN chat—on public Wi-Fi, a VPN helps keep your data encrypted and private." },
            { "firewall", "You asked about firewalls; ensure yours is enabled and configured to block unwanted traffic." },
            { "ransomware", "We discussed ransomware; maintain offline backups so you can recover if files get encrypted." },
            { "data encryption", "You were curious about encryption; encrypt sensitive files at rest and use TLS in transit." },
            { "social engineering", "Remember our social engineering talk; stay vigilant against manipulative techniques." },
            { "software updates", "We covered software updates; installing patches promptly is one of the best defenses." },
            { "backup", "You asked about backups; follow the 3-2-1 rule—three copies, two media types, one off-site." },
            { "password manager", "We discussed password managers; using one helps you create and store strong, unique passwords." },
            { "strong passwords", "You wanted to know about strong passwords; aim for at least 12 characters with mixed symbols." },
            { "public wifi", "Recall public Wi-Fi advice—always use a VPN and avoid logging into sensitive accounts without it." }  
        };

        //-------------------End of File-------------------
    }
}
