using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace POEpart1.Dictionaries
{
    public static class MainResponces
    {
        //generated by ChatGPT
        //-------------------------------------------------
        public static Dictionary<string, string[]> responses = new Dictionary<string, string[]>
        {
            ["how are you"] = new[]
        {
            "I'm doing great—thanks for asking!",
            "All systems green over here!",
            "Feeling fantastic, how about you?",
            "I'm well and ready to help!",
            "Pretty good, thanks! What can I do for you today?"
        },

            ["what is your purpose"] = new[]
        {
            "My purpose is to educate you on cybersecurity topics.",
            "I'm here to help you learn about staying safe online.",
            "I exist to answer your questions about cyber safety.",
            "My job is to guide you through security best practices.",
            "I’m designed to assist you with all things cybersecurity."
        },

            ["what can I ask you about"] = new[]
        {
            "You can ask me about passwords, malware, phishing, and more.",
            "Feel free to quiz me on any cybersecurity topic you like.",
            "I can discuss topics from VPNs to data encryption.",
            "Ask me about firewalls, backups, or two-factor authentication.",
            "I'm here for anything security-related—from viruses to Wi-Fi safety."
        },

            ["virus"] = new[]
        {
            "A virus is malicious software that replicates by infecting files.",
            "Think of a computer virus like a biological one—it spreads file to file.",
            "This malware attaches itself to programs and can corrupt data.",
            "A virus self-replicates and may damage your system or steal info.",
            "In cybersecurity, a virus is code that hides in other executables."
        },

            ["password"] = new[]
        {
            "A password is a secret string you use to protect your accounts.",
            "Think of your password as the key to your digital front door.",
            "It’s a private phrase that only you should know and never share.",
            "Strong passwords mix letters, numbers, and symbols for security.",
            "Treat your password like cash—keep it safe and unique per site."
        },

            ["phishing"] = new[]
        {
            "Phishing is a scam where attackers pose as someone you trust.",
            "It often uses fake emails or websites to steal your credentials.",
            "Think twice before clicking links in unsolicited messages.",
            "Phishing exploits human trust to capture your private info.",
            "Always verify the sender before entering passwords online."
        },

            ["two-factor authentication"] = new[]
        {
            "Two-factor authentication (2FA) adds a second step after your password.",
            "2FA might send you a one-time code via SMS or an authenticator app.",
            "This extra layer helps keep attackers out, even if they have your password.",
            "Enable 2FA to make it much harder for someone to hijack your account.",
            "With 2FA, you need something you know (password) and something you have (code)."
        },

            ["malware"] = new[]
        {
            "Malware is any software designed to harm or exploit your device.",
            "This umbrella term covers viruses, worms, ransomware, and more.",
            "Malware can steal, encrypt, or delete your data without permission.",
            "Always keep your antivirus up to date to catch new malware strains.",
            "Downloading from untrusted sources is a common way to get malware."
        },

            ["vpn"] = new[]
        {
            "A VPN creates a secure, encrypted tunnel between you and the internet.",
            "With a VPN, your data is hidden from eavesdroppers on public Wi-Fi.",
            "Virtual Private Networks mask your IP address for added privacy.",
            "A VPN can help keep your browsing history private from your ISP.",
            "Use a reputable VPN service whenever you’re on an unsecured network."
        },

            ["firewall"] = new[]
        {
            "A firewall monitors and filters incoming and outgoing network traffic.",
            "Think of a firewall as a gatekeeper for your computer’s connections.",
            "It can block unauthorized access while allowing safe communications.",
            "Most operating systems include a built-in software firewall you can enable.",
            "A hardware firewall sits between your router and the internet for extra protection."
        },

            ["ransomware"] = new[]
        {
            "Ransomware encrypts your files and demands payment for the key.",
            "Never pay the ransom—there’s no guarantee you’ll get your data back.",
            "Keep offline backups so you can restore your files if attacked.",
            "Ransomware often spreads via malicious email attachments.",
            "Invest in good antivirus software to detect ransomware before it runs."
        },

            ["data encryption"] = new[]
        {
            "Data encryption scrambles your information so only authorized parties can read it.",
            "Encrypted data looks like gibberish unless you have the decryption key.",
            "Use encryption at rest (on disk) and in transit (over the network) for full protection.",
            "Many apps offer end-to-end encryption so even the provider can’t read your data.",
            "Strong encryption algorithms keep your private info safe from prying eyes."
        },

            ["social engineering"] = new[]
        {
            "Social engineering tricks people into giving away confidential information.",
            "It relies on psychological manipulation rather than technical hacking.",
            "Attackers might pretend to be IT support or a trusted colleague.",
            "Always verify requests for sensitive data, even if they seem urgent.",
            "When in doubt, call the person back at a known number before sharing info."
        },

            ["software updates"] = new[]
        {
            "Software updates patch security holes and fix bugs.",
            "Keeping programs up to date is one of the easiest ways to stay secure.",
            "Many attacks exploit vulnerabilities that vendors have already patched.",
            "Enable automatic updates to ensure you never miss a critical patch.",
            "Outdated software is a common entry point for malware infections."
        },

            ["backup"] = new[]
        {
            "A backup is a copy of your data stored separately in case of loss.",
            "Follow the 3-2-1 rule: three copies, on two different media, one off-site.",
            "Regular backups let you recover quickly from hardware failure or ransomware.",
            "Test your backups occasionally to make sure they actually work.",
            "Cloud backup services can automate the process for you."
        },

            ["password manager"] = new[]
        {
            "A password manager securely stores your login credentials in one place.",
            "It can generate long, random passwords so you never reuse the same one.",
            "Most password managers autofill your passwords in the browser or apps.",
            "Protect your vault with a strong master password and enable 2FA.",
            "Using a password manager is far safer than memorizing or writing down passwords."
        },

            ["strong passwords"] = new[]
        {
            "Strong passwords are at least 12 characters long and mix letters, numbers, and symbols.",
            "Avoid dictionary words or easily guessed phrases like birthdays or pet names.",
            "A passphrase of unrelated words can be both strong and memorable.",
            "Use uppercase, lowercase, digits, and special characters for best results.",
            "Change your passwords regularly and never reuse them across sites."
        },

            ["public wifi"] = new[]
        {
            "Public Wi-Fi networks are often unencrypted and open to eavesdropping.",
            "Avoid logging into banking or email accounts unless you use a VPN.",
            "Always check the network name with staff to avoid ‘evil twin’ hotspots.",
            "Set your Wi-Fi profile to ‘public’ so your device won’t share files or printers.",
            "Turn off automatic connection to open networks to prevent unwanted joins."
        }
        };
        //-------------------------------------------------






    }
}
