# .github/workflows/main.yml

name: .NET Framework CI

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore POEpart2/POEpart1.sln  

    - name: Build Solution
      run: msbuild POEpart2/POEpart1.sln /p:configuration-Release

    - name: Success message
      run: echo "✅ Build completed successfully!"
